#pragma once

#define CHORDAL_HOLD

#define TAPPING_TERM 200
// #define TAPPING_TERM_PER_KEY
// #define PERMISSIVE_HOLD
// #define QUICK_TAP_TERM_PER_KEY

#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX
