COMBO_ENABLE = yes
REPEAT_KEY_ENABLE = yes

UNICODE_ENABLE = no
UCIS_ENABLE = no
UNICODEMAP_ENABLE = no
UNICODE_COMMON = yes

EXTRAKEY_ENABLE = yes

DYNAMIC_MACRO_ENABLE = yes

AUTOCORRECT_ENABLE = yes
LAYER_LOCK_ENABLE = yes

DEFERRED_EXEC_ENABLE = yes
