COMBO_ENABLE = yes
REPEAT_KEY_ENABLE = yes

UNICODE_ENABLE = no
UCIS_ENABLE = no
UNICODEMAP_ENABLE = no
UNICODE_COMMON = yes

# EXTRAKEY_ENABLE = yes
# LTO_ENABLE = yes
# MOUSEKEY_ENABLE = no

# AUTOCORRECT_ENABLE ?= yes
# CAPS_WORD_ENABLE ?= yes
# CONSOLE_ENABLE ?= no
# GRAVE_ESC_ENABLE ?= no
# LAYER_LOCK_ENABLE ?= yes
# NKRO_ENABLE ?= no
# RGB_MATRIX_CUSTOM_USER ?= yes
# SPACE_CADET_ENABLE ?= no
# TAP_DANCE_ENABLE ?= no

SELECT_WORD_ENABLE ?= yes
ifeq ($(strip $(SELECT_WORD_ENABLE)), yes)
	OPT_DEFS += -DSELECT_WORD_ENABLE
	SRC += features/select_word.c
endif
