COMBO_ENABLE = yes
REPEAT_KEY_ENABLE = yes

UNICODE_ENABLE = no
UCIS_ENABLE = no
UNICODEMAP_ENABLE = no
UNICODE_COMMON = yes

EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = no

AUTOCORRECT_ENABLE ?= yes
LAYER_LOCK_ENABLE ?= yes
RGB_MATRIX_CUSTOM_USER ?= yes

ORBITAL_MOUSE_ENABLE ?= yes
ifeq ($(strip $(ORBITAL_MOUSE_ENABLE)), yes)
	MOUSE_ENABLE = yes
	OPT_DEFS += -DORBITAL_MOUSE_ENABLE
	SRC += features/orbital_mouse.c
endif
